name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push'
        required: true
        type: boolean
        default: true
      tag:
        description: 'Tag'
        required: true
        type: string
        default: 'latest'
      cache:
        description: 'Cache'
        required: true
        type: boolean
        default: true

env:
  PUSH: ${{ github.event.inputs.push }}
  TAG: ${{ github.event.inputs.tag }}
  CACHE: ${{ github.event.inputs.cache }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      # Add support for more platforms with QEMU (optional)
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ env.PUSH }}
          tags: ghcr.io/mo-mo-666/latex-ubuntu:${{ env.TAG }}
          cache-from: ${{ env.CACHE && 'type=registry,ref=ghcr.io/mo-mo-666/latex-ubuntu:cache' || '' }}
          cache-to: ${{ env.CACHE && 'type=registry,ref=ghcr.io/mo-mo-666/latex-ubuntu:cache,mode=max' || '' }}
          build-args: |
            CACHE=${{ env.CACHE }}
            TAG=${{ env.TAG }}
          platforms: linux/amd64
          outputs: |
            type=registry,push=true,ref=ghcr.io/mo-mo-666/latex-ubuntu:cache
            type=image,push=true,ref=ghcr.io/mo-mo-666/latex-ubuntu:${{ env.TAG }}
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_INLINE_CACHE: 1
